### ISSUE TITLE
[1.7.10] ConcurrentModificationException

### ISSUE THREAD

**Issue by jsaggers** [elix-x/Avoid-Exploding-Creepers#2] opened 2016-05-01 04:16 UTC
Just walking in my knew world and I get [this crash](http://pastebin.com/yy0QXhbj)
Using 1.7.10, forge 1614, excore 1.4.1 and the latest version of creeper awareness which is 2.0 correct.

**Comment by Elix-x** [comment] 2016-05-01 07:49
Duplicate of #1.

**Comment by Elix-x** [comment] 2016-05-01 07:50
I don't know how exactly this happens nor what it is causing this.
This crash is very rare and random, and has never happened to me.
But i'm still trying to solve it.

**Comment by jsaggers** [comment] 2016-05-02 08:17
It is very random, sorry I didn't mean to post a duplicate post.

**Comment by Elix-x** [comment] 2016-05-02 15:22
Double post is not a problem.
This crash being very random is.

**Closed as completed** 2016-05-16 14:56 UTC
Labels: duplicate, Crash
